### ISSUE TITLE
When counts are present, query tooltips appear offscreen

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/cilantro#751]
When the counts are shown on the Workspace page, the private queries are shown above the public queries on the right hand side of the page. The issue with this is that the tooltips in the query items are set to pop out right so, when the counts are present, the tooltips appear offscreen as shown below. Moving the tooltip to the left side should solve the issue in all cases.

![screen shot 2014-12-09 at 11 01 34 am](https://cloud.githubusercontent.com/assets/3911912/5360527/1675e306-7f93-11e4-99b3-d0aca9538f50.png)

**Comment by hassanNS** [comment]
I'll try resolving this today
