### ISSUE TITLE
Include csrf with Cilantro

### ISSUE THREAD

**Issue by sgithens** [chop-dbhi/cilantro#770]
It might be nice to bundle csrf.js with Cilantro natively rather than including separately (as an example is done in verify, which is where I looked to, in order to incorporate it in my own project). 

https://github.com/chop-dbhi/varify/blob/9094abbe86fc2b6260720711baa66c6e124b7ab7/varify/static/js/src/csrf.js

A simple configuration option for Cilantro to enable it would then be nice.  

I'm suggesting this for inclusion because I feel like it would be necessary for a vast majority of Django projects where harvest is complementing other functionality in someones existing application.

**Comment by bruth** [comment]
@sgithens A long time coming, but #779 adds support for this.

**Comment by sgithens** [comment]
That's great!  Thanks @bruth
