### ISSUE TITLE
API display button

### ISSUE THREAD

**Issue by leipzig** [chop-dbhi/cilantro#777]
This button should display a pop-up panel containing the JSON and associated raw `curl` and python `urllib` syntax for accessing the results of a user-created query from the command line or a script.
![mockup](https://cloud.githubusercontent.com/assets/147991/13433156/a19a3286-df9e-11e5-8bce-431d916ece9f.png)

**Comment by leipzig** [comment]
@bruth any thoughts about this?

**Comment by bruth** [comment]
This looks good, thank you for mocking this up. Where do you expect the button to open this dialog would be placed? It will likely be used the most in the results page, but it may be useful in the workspace for saved queries.

**Comment by leipzig** [comment]
yes, i was thinking next to Save/Share Query buttons

there is some precedence for this feature in 
http://useast.ensembl.org/biomart/martview

but i'm sure you can do something slicker

**Comment by leipzig** [comment]
any movement on this?

**Comment by bruth** [comment]
Yes, it will be implemented this week.
